config/routes.rb
Rails.application.routes.draw do
  mount API => "/api"

  resources :groups, except: [:index, :show] do
    post 'add_user'
    delete 'leave'
  end

  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      root to: 'devise/sessions#new'
    end
  end

  root to: 'chats#index', as: 'chats_index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :messages, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups
  has_many :messages

  validates :name, presence: true, length: { maximum: 20 }
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    chats_index_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @user = current_user
    @groups = @user.groups.all
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)
    if current_user.save
      flash[:notice] = "グループを作成しました。"
      redirect_to chats_index_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
    @user = User.new
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:notice] = "グループを編集しました。"
      redirect_to chats_index_path
    else
      render 'edit'
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    flash[:notice] = "グループを削除しました。"
    redirect_to chats_index_path
  end

  def add_user
    @user = User.find_by(add_user_params)
    if @user
      @group = current_user.groups.find(params[:group_id])
      @group.users << @user
      flash[:notice] = "グループにユーザを追加しました。"
    else
      flash[:alert] = "指定されたユーザは存在しません。"
    end

    redirect_to chats_index_path
  end

  def leave
    current_user.groups.delete(params[:group_id])
    flash[:notice] = "グループから抜けました。"
    redirect_to chats_index_path
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

  def add_user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/chats/index.html.erb
<!-- left -->
<div class="col-sm-3">
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button"
            id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
      <span class="glyphicon glyphicon-user"></span>
      <%= @user.name %>
      <span class="caret"></span>
    </button>

    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
      <li role="presentation"><%= link_to "グループ作成", new_group_path %></li>
      <li role="presentation"><%= link_to "ユーザ編集", edit_user_registration_path %></li>
      <li role="presentation"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>

  <div class="panel panel-default chat-groups">
    <div class="panel-heading">参加グループ</div>
    <div class="list-group">
      <% @groups.each do |group| %>
        <%= link_to group.name, "##{group.name}", class: "list-group-item my-group", id: group.id %>
      <% end %>
    </div>
  </div>
</div>

<!-- center -->
<div class="col-sm-6">
  <div class="row spacer20">
    <div class="col-xs-10">
      <textarea id="message-post-area" class="form-control message-post-area"
        rows="2" placeholder="送信するメッセージを入力"></textarea>
    </div>
    <div class="col-xs-2 send-button-div">
      <button type="button" class="btn btn-primary btn-lg disabled send-button">送信</button>
    </div>
  </div>

  <div class="panel panel-primary timeline">
    <div class="panel-heading timeline-header">タイムライン</div>
    <div class="list-group timeline-body">
      <li class="list-group-item group-not-selected">グループが選択されていません</li>
    </div>
  </div>
</div>

<!-- right -->
<div class="col-sm-3">
  <div class="list-group">
    <%= link_to "グループ編集", "#", class: "list-group-item disabled group-setting" %>
    <%= link_to "グループを抜ける", "#", class: "list-group-item disabled leave-group",
      method: :delete, data: { confirm: "Are you sure?" } %>
  </div>

  <div class="panel panel-default chat-groups">
    <div class="panel-heading">メンバー</div>
    <div class="list-group group-member"></div>
  </div>
</div>

app/views/groups/_error_messages.html.erb
<% if @group.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <h2><%= @group.errors.count %>個のエラーにより、groupを保存できませんでした：</h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%= render 'error_messages', object: @group %>

<div class="col-sm-6 col-sm-offset-3">
  <div class="jumbotron">
    <h2>Edit Group</h2>

    <%= form_for(@group) do |f| %>
      <div class="field form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>

      <div class="actions form-group">
        <%= f.submit "Update", class: 'btn btn-success', data: { disable_with: '更新中...' } %>
      </div>
    <% end %>

    <hr>

    <h3>Add User</h3>

    <%= form_for(@user, url: {controller: :groups, action: :add_user, group_id: @group.id}) do |f| %>
      <div class="field form-group">
        <%= f.label :email %> <i>(exact match)</i><br />
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="actions form-group">
        <%= f.submit "Add", class: 'btn btn-success', data: { disable_with: '追加中...' } %>
      </div>
    <% end %>

    <hr>

    <h3>Delete Group</h3>

    <%= button_to "Delete", @group, data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger' %>

    <hr>

    <%= link_to "Back", chats_index_path %>

  </div>
</div>

app/views/groups/new.html.erb
<%= render 'error_messages', object: @group %>

<div class="col-sm-6 col-sm-offset-3">
  <div class="jumbotron">
    <h2>Create Group</h2>

    <%= form_for(@group) do |f| %>
      <div class="field form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>

      <div class="actions form-group">
        <%= f.submit "Create", class: 'btn btn-success', data: { disable_with: '作成中...' } %>
      </div>
    <% end %>

    <hr>

    <%= link_to "Back", chats_index_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupChat</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header class="navbar navbar-default navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'グループチャット', root_path, class: 'navbar-brand' %>
        </div>
      </div>
    </header>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>